### PR TITLE
Fix some messages

### PR DESCRIPTION
**Pull request by riku6460**

### CODE REVIEW

**Review by Proximyst — CHANGES_REQUESTED** [review]
Using only one quotation mark will render it unused. `''` becomes `'`, and `'` becomes a literal and is not present in the resulting string.

This means that e.g. `no_server_permission` will now do `You dont` instead of `You don't` in the message the player sees.

**Comment by riku6460** [comment]
Waterfall build 379 outputs the following because of this. https://github.com/PaperMC/Waterfall/blob/7b4d6e99a98216175470bdb3c0f8c4cc3563a78b/BungeeCord-Patches/0016-Micro-optimizations.patch#L18-L21

**Comment by Proximyst** [comment]
Could've sworn that was how properties were (properly hehe) loaded. In that case, at least do it to every message with this issue.

**Comment by riku6460** [comment]
I think already fixed all messages.

**Comment by Janmm14** [comment]
The correct solution would be to make the no-argument message getter replace `''` with `'`.
This way waterfall has to maintain fewer changes while staying 100% compatible with bungeecord's message properties format.

And the two `''` have to stay in messages which take argument, as for those, MessageFormat is still used. So the current optimization creates confusing, inconsistent behaviour and should be corrected.

**Pull request closed without merging**
