### PR TITLE
Providing access to the player's LoginResult on LoginEvent

### PR DESCRIPTION
**Pull request by phenomax**
Adds the feature requested in #154 
@jamierocks Sorry for the delay!

### CODE REVIEW

**Comment by jamierocks** [comment]
Apologies, I completely missed this - I'll take a look later ;)

**Comment by mikroskeem** [comment]
Any updates on this?

**Comment by jamierocks** [comment]
Seems reasonable - I'll get this merged tonight ;)

**Comment by jamierocks** [comment]
Merged https://github.com/WaterfallMC/Waterfall/commit/9f73d70f1507a27b0317837c8033880d61a42c9c

**Pull request closed without merging**
