### PR TITLE
Fix #178 Error decoding packet unknown with contents

### LINKED ISSUE #178: Error decoding packet unknown with contents
I use latest build Waterfall (#147) and some time ago began to receive such error

Latest build paper spigot 1.12 (with latest ViaVersion 1.3.0)
https://pastebin.com/SVn8qBuG

Latest build paper spigot 1.8.8 (with latest ViaVersion 1.3.0)
https://pastebin.com/k0Ge5qVc

### PR DESCRIPTION
**Pull request by Polyana-Fontes**
It was happening on my server too and this changed fixed the issue.

This is my first time pushing changes to a patch-based repository, let me know if I did anything wrong generating this patch.

I only added:
```java
            if ( in.readerIndex() == in.writerIndex() )
            {
                return;
            }
```

to the MinecraftDecoder.decode() method as the error happens when the ByteBuf has no byte available to be read.

### CODE REVIEW

**Comment by MarkTwoFive** [comment]
If the error occurrs when there's no byte available to read wouldn't ``InputStream#available`` be a better way to determine when to exit early?

**Comment by astei** [comment]
@MarkL4YG Netty doesn't use `InputStream`s, it uses `ByteBuf`s.

**Comment by jamierocks** [comment]
Can anyone confirm that this resolves #178?

**Comment by PurpleIsEverything** [comment]
Tested this recently with no negative effects it remains to be seen if it's actually doing anything.

**Comment by Fejm** [comment]
Tested & working

**Comment by PurpleIsEverything** [comment]
@jamierocks Please merge this it works totally fine.

**Comment by electronicboy** [comment]
I'm pretty sure I stated this on IRC a while back, The issue here is that something is sending/throwing out invalid data somewhere. This "works" as a means for bodging around the issue, but isn't a fix whatsoever

**Comment by jamierocks** [comment]
Having looked into this more closely a while back, I'm inclined to agree on that. However, I would like to avoid kicking players.

**Comment by MarkTwoFive** [comment]
Sounds reasonable enough. I would suggest keeping the issue open labeling it something like "work-around deployed" after merging so it doesn't get lost just because it's suppressed

**Pull request closed without merging**
