### PR TITLE
1.19.4 Support

### PR DESCRIPTION
**Pull request by linsaftw**

### CODE REVIEW

**Review by electronicboy — APPROVED** [review]

**Comment by MiniDigger** [comment]
thanks!

**Comment by linsaftw** [comment]
👏👍

**Comment by ArzuAkmalR** [comment]
[18:04:07 WARN]: [/140.213.13.56:50170|ItzArzzu] <-> DownstreamBridge <-> [lobby] - could not decode packet! java.lang.IllegalArgumentException: No provider for argument e�,color�,�,�,�,deathMessageVisibility�,
                                                                  displayName�,
                                                                               friendlyFire�,�,�,�,nametagVisibility�
What is that?

**Comment by linsaftw** [comment]
> [18:04:07 WARN]: [/140.213.13.56:50170|ItzArzzu] <-> DownstreamBridge <-> [lobby] - could not decode packet! java.lang.IllegalArgumentException: No provider for argument e�,color�,�,�,�,deathMessageVisibility�, displayName�, friendlyFire�,�,�,�,nametagVisibility� What is that?

Check if it comes from BungeeCord 1.19.4 compatibility itself.

**Comment by Janmm14** [comment]
https://github.com/SpigotMC/BungeeCord/commit/f4534c8273d9db5323fe6c9ae34a3e210c56f030

**Comment by linsaftw** [comment]
> [SpigotMC/BungeeCord@f4534c8](https://github.com/SpigotMC/BungeeCord/commit/f4534c8273d9db5323fe6c9ae34a3e210c56f030)

Trying to pull but there are a lot of conflicts. I am doing something wrong?

**Comment by HaiXi2912** [comment]
Do not use bungee to enter, single end entry is allowed

[18:40:03 INFO]: [Hai_Xi] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[18:40:03 INFO]: [/120.87.xxx.xxx:16841|Hai_Xi] -> UpstreamBridge has disconnected
[18:40:03 INFO]: [/120.87.xxx.xxx:16841|Hai_Xi] <-> DownstreamBridge <-> [lobby] has disconnected
[18:40:05 INFO]: [/120.87.xxx.xxx:16848] <-> InitialHandler has connected
[18:40:05 INFO]: [Hai_Xi|/120.87.xxx.xxx:16848] <-> ServerConnector [lobby] has connected
[18:40:05 WARN]: [/120.87.xxx.xxx:16848|Hai_Xi] <-> DownstreamBridge <-> [lobby] - could not decode packet! java.lang.IndexOutOfBoundsException: index: 2, length: 64 (expected: range(0, 35))

**Pull request merged**
