### PR TITLE
1.16.2 Temporary support patch 

### PR DESCRIPTION
**Pull request by Xernium**
@electronicboy there you go.

### CODE REVIEW

**Comment by fierceeo** [comment]
It works nicely, except I have an issue with resource packs kicking players. (I'm not sure if this is 100% revenant to this though)

**Comment by Xernium** [comment]
@ramdon-person are you using a plugin for that?

**Comment by fierceeo** [comment]
Yes, bungee resource packs. (The development build for 1.16)

**Comment by Xernium** [comment]
The plugin has no valid packet offset for 1.16.2 yet, it has changed from 1.16.1, so naturally this will cause this kind of issue. Not a Bungeecord issue itself

**Comment by Xernium** [comment]
https://github.com/Phoenix616/ResourcepacksPlugins/blob/master/bungee/src/main/java/de/themoep/resourcepacksplugin/bungee/packets/ResourcePackSendPacket.java#L58 should now be 0x38

**Comment by fierceeo** [comment]
oh okay good to know. I'll update that and use it. Thanks

**Comment by fierceeo** [comment]
oh I didn't see, it looks like the plugin's owner just updated it

**Pull request merged**
