### PR TITLE
Add missing permission nodes

### PR DESCRIPTION
**Pull request by mikroskeem**
Allows to put /bungee and /perms behind permission nodes

### CODE REVIEW

**Comment by Janmm14** [comment]
not a fan of adding a permission node to /bungee - all it provides is security by obscurity while making waterfall less popular

**Comment by mikroskeem** [comment]
I mean people can already do that with `disabled_commands`, so if they really wanted security by obscurity then they can have it.

**Comment by Janmm14** [comment]
But if you add permission node, default behaviour changes.

**Comment by mikroskeem** [comment]
Sure, might reconsider dropping /bungee from this patch. What about /perms? In my opinion it's pretty useless if you have custom permissions plugin (handling permission checks via an event)

**Pull request closed without merging**
