### PR TITLE
Updated Upstream (BungeeCord)

### PR DESCRIPTION
**Pull request by tomcraft**
Upstream has released updates that appears to apply and compile correctly.
This update has not been tested by PaperMC and as with ANY update, please do your own testing

BungeeCord Changes:
6f7331e8 #3138, 3140: Check for the new leak detector netty flag
1b489bcc Attempt to fix java 8 native crash
da27924a #3115, #3125: Update natives build script, switch to Cloudflare zlib
15b39887 #3133: Directly disconnect on illegal chars
f9583a76 #3129: Replace ConnectTimeoutException with a more user-friendly string.
cb738188 #3126: Use suppliers instead of reflection for native impl generation.
a8b2f526 #3123: Apply exact vanilla string length limits for tab completion
ad50fc9a #3111: Check chat for illegal chars & moved length check into the packet class

### CODE REVIEW

**Comment by tomcraft** [comment]
Tested with macOS 11.4, natives are loading and I can connect to the proxy.

**Review by ghost — CHANGES_REQUESTED** [review]
They just released a new commit 3 minutes ago.

**Review by electronicboy — APPROVED** [review]

**Comment by tomcraft** [comment]
> They just released a new commit 3 minutes ago.

I'll update in a few

**Comment by tomcraft** [comment]
squashed commits, also tested with debian

**Review by ghost — APPROVED** [review]

**Comment by tomcraft** [comment]
updated again to latest upstream and force pushed

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Waterfall/commit/ee819df91fccd47d0bbbe7974169743526bec459
Looks like githubs tool was stupid and was still pulling an older copy of this even after I removed the branch *sigh*

**Pull request closed without merging**
