### PR TITLE
Improved TabCompleteResponseEvent

### PR DESCRIPTION
**Pull request by Joo200**
- Give access to Brigadier's Suggestions object.
- Access to the list of suggestions through a self written list class

### Reasons for the change:
The TabCompleteResponseEvent from BungeeCord has a new behavior with Minecraft's Brigadier:
1. Load all TabCompletions from spigot in the Suggestions object.
2. Move the text from all TabCompletions in a ArrayList.
3. Call the TabCompleteResponseEvent
4. If the event changed single TabCompletions: Create a new Suggestions object from the ArrayList. Drop all existing Tooltips.

There will probably be no plugin that offers tooltips. But it will only be a matter of time before problems arise with this handling.

I tested it with Spigot 1.13.2 and Spigot 1.12.2

### Questions:
- Should I add some test cases?
- This might be an interesting idea for TabCompleteEvent.
- Add a config variable to enable this handling?

### CODE REVIEW

**Comment by electronicboy** [comment]
Sorry for the delay, kept starting to reply on this and I just never seem to finish

Two main points, 

The first being that we shouldn't be exposing brigadier objects (brigadiers only accessible in the API due to it being used in the protocol, ideally brigadier shouldn't be visible here), they're not ours and we cannot guarantee any form of consistency, as such they are not suitable for API here

currently ill so don't really want to comment on every issue in SuggestionList, but last I looked there was one or two methods which looked wrong, e.g. `toArray(T[] a)` does not conform to behavior expected from List

**Comment by Joo200** [comment]
Okay, instead of showing brigadier there should be an own implementation of suggestions.
I understand the point of consistency.

Do you think the implementation of a "forwarding" list is acceptable?
I don't want to invest time in this solution only to get a denied PR ;)

**Comment by compieter-gh** [comment]
I have seen an issue where if a server send the tabcompletelist too bungeecord it doesn't reset on server switch which should happen and request a new tabcompletelist from the joined server am i correct?

**Comment by Joo200** [comment]
ComPieter1, that doesn't have anything to do with that pull request.

I forgot totally about that PR. As there are some better ideas (Paper's brigadier implementation) I'll close that PR.

**Pull request closed without merging**
