### PR TITLE
Preliminary 1.17 support

### PR DESCRIPTION
**Pull request by Xernium**
Here we go again; 
I'm tracking the changes up to 1.17 so this is merge-ready when its released.
This is a byproduct of https://github.com/VelocityPowered/Velocity/pull/382 which I am prioritizing over this.

If you want to run a build of this either compile it yourself or use one of the milestones from  https://github.com/Xernium/Waterfall/releases 

If you encounter issues please comment on this PR or open an issue on my fork.

### CODE REVIEW

**Comment by Xuwznln** [comment]
Really a nice job. But I am getting some errors with 20w51a and 21w03a recently.
The first one is that any potion effect will cause player disconnect, but the console log is normal.
The second one is this:
[Netty Worker IO Thread #7/WARN]: [/39.187.231.241:31521|lky] <-> DownstreamBridge <-> [PreviewServer] - overflow in packet detected! Cannot receive string longer than Short.MAX_VALUE (got 1822273 characters)

Really hope that there can be a fix on this. Thanks!

**Comment by Xernium** [comment]
@Xuwznln I can not reproduce your issue. 
Bildschirmfoto 2021-01-31 um 14 46 30
Please provide me with:
- Description of your setup
- Complete list of plugins on the proxy (yes those matter a lot in this case as they may not work with the snapshots) 
- Complete list of mods or plugins on the downstream server
- A way to reproduce this issue

**Comment by Xuwznln** [comment]
Snapshot 21w03a Waterfall
21w03a fabric server with fabric-installer-0.6.1.51_2 and fabric-api-0.29.5+1.17
and other paper servers.

proxy plugins:
- BungeeResourcepacks
- LuckPerms
- SkinsRestorer
- BungeeCommandBlocker
- PartyAndFriends
- AnnouncementsEverywhere
- Triton
- Friends-Online-Info-On-Join-For-PAF
- BungeePluginManager
- TTCW
- AntiFakePlayer
- BungeeTabListPlus
- BungeeBan

fabric server mods:
- fabric-api-0.29.5+1.17
- fabric-carpet-21w03a-1.4.24 v210120
- FabricProxy-1.4.6   (link:  https://github.com/OKTW-Network/FabricProxy)

This only happens when the potion effect is expired.
This also happens when in other 1.16.4 servers with viaversion-dev-21w03a support

**Comment by Xernium** [comment]
@Xuwznln It **has** to be a plugin or mod causing this. I don't suspect its the carpet mod on the server, I suspect its a Bungee plugin. I tried it with a 1.16.5 paper server with the ViaVersion-dev release and a snapshot server running the same fabric, fabric-api and fabric-proxy. Please try to find it by removing plugins one by one until it stops.

**Comment by Xuwznln** [comment]
Yes, I do found the plugin named BungeeResourcePacks causing preview clients to disconnect.
I am going to create a issue there, thanks for your help.

**Comment by compieter-gh** [comment]
@Xernium I got a question when will 20w07a will be released i tried updating it myself but it seems some off the packets might have changed and i have totally no knowledge bout java. Thank you if can add me on discord ComPieter#0001

**Comment by Xernium** [comment]
@TheCompieter Was busy yesterday. Done.

**Comment by compieter-gh** [comment]
Thank you.

**Comment by AcrossTheGreatWallWeCanReachTheWorld** [comment]
Any updates for this PR?

**Comment by Xernium** [comment]
I will update this PR when I find the time. I’m hard-locked between work and exams at the moment. That’s over roughly in about one and a half weeks

**Comment by Chew** [comment]
BungeeCord has 1.17 now?

**Comment by Xernium** [comment]
This PR is going in the bin now, I’ll rather update upstream now since md_5 decided to be open about this! 🎉

**Pull request closed without merging**
