### PR TITLE
Use Log4j for logging

### PR DESCRIPTION
**Pull request by Foorack**
Default log file is logs/proxy.log with rollover daily and on startup. Console and file output format is the same.

- All Log4j loggers are asynchronous
- Supports Loggers created through j.u.l.Logger.getLogger()

Credits goes to zreed!
https://github.com/zreed/BungeeCord/commit/3c8cba3ce9c7953b73fed7af3d7ef89a2a322353

This patch should be removed if it is decided that the pull request in BungeeCord should be merged. There are many advantages to using log4j, please read the parent pull request for more information.

### CODE REVIEW

**Comment by Techcable** [comment]
I think we should use slf4j for logging, so we're more insulated from the underlying implementation. Do you have any objections to that @zreed ?

**Comment by zreed** [comment]
I went with Log4j mainly due to its use in Minecraft (feature parity) and its more efficient translation of j.u.l logging. Why not just also add slf4j-api to the API & slf4j->log4j2 to the Proxy?

**Comment by Techcable** [comment]
I will, just wanted your feedback. Thanks for helping improve our logging situation!

**Comment by Foorack** [comment]
Hello. :) Any status update on this? Can it be merged?

**Comment by Foorack** [comment]
@Techcable Ping. This nearly 3 months old now.

**Comment by jamierocks** [comment]
No longer necessary, having merged https://github.com/WaterfallMC/Waterfall/pull/176.

**Pull request closed without merging**
