### PR TITLE
Properly check that the channel is closed

### PR DESCRIPTION
**Pull request by xxDark**

### CODE REVIEW

**Comment by Black-Hole** [comment]
What issue are you trying to fix?
How do you confirm that it's fixed?

**Comment by xxDark** [comment]
> 
> 
> What issue are you trying to fix?
> How do you confirm that it's fixed?

Bungeecord sometimes continues to write to the channel, even if it closed.
attachment

**Comment by xxDark** [comment]
You can see it by yourself by logging all the exceptions in `HandlerBoss#exceptionCaught`

**Comment by colinrgodsey** [comment]
I have noticed this before. Need to fully understand when TCP channels go inActive vs closing... I believe the 'active' state changes immediately, then 'close' doesn't fulfill until the underlying socket itself is closed (which may have to wait on a selector channel).

**Comment by MrIvanPlays** [comment]
`// Waterfall` comment is missing when you do that change.

**Comment by electronicboy** [comment]
This has already made it upstream, oh so long ago...
#LongLiveTheCat

**Pull request closed without merging**
