### PR TITLE
Improve the ServerKickEvent to fire when a server crashes or shuts do…

### PR DESCRIPTION
**Pull request by fuzzybot**
…wn too fast, and include the Cause

### CODE REVIEW

**Comment by Techcable** [comment]
Would this break backwards compatibility somehow?

**Comment by Techcable** [comment]
Merged manually

**Comment by nathan818fr** [comment]
I just want to point out that this is the pull request that I sent to BungeeCord (https://github.com/SpigotMC/BungeeCord/pull/1851).
This is a few lines of code and I don't care, but quoting my username would have been the minimum @fuzzybot :/

**Comment by jamierocks** [comment]
I would like to apologies on behalf of the Waterfall team. I'll rewrite the patch to have you as the author.

**Comment by jamierocks** [comment]
https://github.com/WaterfallMC/Waterfall/commit/d2d44264d2ed93577ca310c54b71d2a37bd27efb

**Pull request closed without merging**
