### PR TITLE
Preliminary 1.18 support

### PR DESCRIPTION
**Pull request by LemonCaramel**
preliminary support for the upcoming 1.18 release

### CODE REVIEW

**Comment by quiquelhappy** [comment]
please merge this already :)

**Comment by LemonCaramel** [comment]
> please merge this already :)

No, this pr currently support 1.18-pre1.
I will update pr at 1.18 release.

**Comment by quiquelhappy** [comment]
why? there are legit use cases for supporting 1.18 already, such as using vanillacord.

**Comment by electronicboy** [comment]
We very rarely commit to following snapshots closely, if this is a need, you are more than welcome to compile it

**Comment by quiquelhappy** [comment]
got it, thanks

**Comment by Xernium** [comment]
Hate to say this but md will likely update Bungeecord before so all that is needed is a patch to skip the SNAPSHOT_SUPPORT var.
That said we’d also happily take that

**Comment by LemonCaramel** [comment]
If md5 updates the bungeecode, I will switch this pr to upstream update.

**Pull request closed without merging**
